// TooManyFunctions: one member per core operation, by design. Splitting the boundary into
// reads/writes interfaces would mean two protocols for Swift to implement and one more thing to
// keep in step with the crate, for no gain — the count tracks the crate's surface, not complexity.
@file:Suppress("TooManyFunctions")

package xyz.lark.app.core.ffi

/**
 * The platform's door to the in-process Rust core (KTD-4).
 *
 * Why a delegate instead of a platform class implementing [xyz.lark.app.core.LarkCore] directly:
 * Kotlin/Native forbids Swift from implementing a Kotlin `suspend` member (KT-38974), and the seam
 * is full of them. So the boundary is deliberately **non-suspend and completion-handler shaped** —
 * a shape Swift can implement — and [xyz.lark.app.core.ffi.DelegateBackedLarkCore] in `iosMain`
 * lifts it back into the suspending seam.
 *
 * The implementation owns the `LarkWallet` handle. No UniFFI type appears here, which is what lets
 * shared code stay ignorant of whether the core is reached through Swift bindings, JNA, or anything
 * else; Android's `FfiLarkCore` will call the Kotlin bindings directly and never use this at all.
 *
 * ## The callback contract
 *
 * Every operation is asynchronous and reports exactly once, on any thread. Two shapes:
 * - value-returning: `onResult(value, error)` — exactly one of the two is non-null.
 * - effect-only: `onDone(error)` — null means it worked.
 *
 * `error` is a human-readable message for logging and health classification, not a typed error:
 * the seam's outcomes ([xyz.lark.app.core.model.SendResult], [xyz.lark.app.core.model.HealthState])
 * are coarser than the crate's error enum, so nothing above needs to branch on the cause.
 *
 * Implementations must never report twice, and must never fail to report — the adapter suspends
 * until the callback fires, so a dropped callback hangs the caller.
 */
interface LarkCoreDelegate {

    /**
     * A fresh 12-word BIP-39 mnemonic, generated by the crate.
     *
     * Asynchronous like everything else here even though the crate's own call is synchronous:
     * a uniform boundary is worth more than saving a hop, and callers are already suspending.
     *
     * Not named `newMnemonic`: Kotlin/Native maps a `new`-prefixed member onto Objective-C's init
     * family, so it would reach Swift as `doNewMnemonic`.
     */
    fun generateMnemonic(onResult: (words: List<String>?, error: String?) -> Unit)

    /**
     * Open the wallet described by [config], creating it from [words] if it is not there yet.
     *
     * Measured at ~2s against real mutinynet with a release build of the crate, creating or
     * opening. It is not instant, though, and the build configuration dominates: the same call takes
     * over a minute against a debug build, which is why the iOS threading experiment recorded ~75s.
     * Everything else here requires this to have succeeded first, and an implementation must report
     * calls made before it does as errors rather than crash.
     */
    fun openWallet(
        config: FfiWalletConfig,
        words: List<String>,
        onDone: (error: String?) -> Unit,
    )

    /** Spendable off-chain balance in sats. */
    fun balanceSats(onResult: (sats: Long?, error: String?) -> Unit)

    /** Wallet maintenance: sync, register boards, refresh VTXOs that are near expiry. */
    fun refresh(onDone: (error: String?) -> Unit)

    /** A fresh Ark receive address. Needs a reachable Ark server. */
    fun mintAddress(onResult: (address: String?, error: String?) -> Unit)

    /** A fresh on-chain deposit address, derived locally. */
    fun depositAddress(onResult: (address: String?, error: String?) -> Unit)

    /**
     * Pay a BOLT11 invoice. [sats] is 0 for an amount-carrying invoice, positive to set the
     * amount on an amountless one. The returned string is a summary for logging, not a receipt.
     */
    fun sendBolt11(invoice: String, sats: Long, onResult: (summary: String?, error: String?) -> Unit)

    /**
     * Pay an Ark address out of round. The other half of send: the app's own receive code is an
     * Ark address, so this is what one lark wallet paying another actually uses.
     */
    fun sendArk(address: String, sats: Long, onResult: (summary: String?, error: String?) -> Unit)

    /**
     * Board everything the on-chain wallet holds into Ark, creating a VTXO.
     *
     * Deliberately amount-free. Boarding an explicit amount equal to the whole confirmed balance
     * cannot work — the board transaction's on-chain fee comes out of the same coins — so an
     * "amount" parameter here would be a trap for the only caller there is.
     */
    fun boardAll(onResult: (summary: String?, error: String?) -> Unit)

    /** Payment history, in whatever order the crate returns; the adapter sorts. */
    fun movements(onResult: (movements: List<FfiMovement>?, error: String?) -> Unit)

    /** Bring the on-chain wallet up to date. Separate from [refresh], which does not touch it. */
    fun onchainSync(onDone: (error: String?) -> Unit)

    /** The on-chain balance as of the last [onchainSync]. */
    fun onchainBalance(onResult: (balance: FfiOnchainBalance?, error: String?) -> Unit)

    /** Spendable VTXOs summarised: how many, how much, and when the first one expires. */
    fun vtxoSummary(onResult: (summary: FfiVtxoSummary?, error: String?) -> Unit)
}

/**
 * Where the wallet lives and what it talks to.
 *
 * One value rather than four parameters because they are one decision — which network's wallet,
 * kept where, against which server and chain source — and they are only ever passed together.
 */
data class FfiWalletConfig(
    val datadir: String,
    val network: String,
    val arkServer: String,
    val esplora: String,
)

/**
 * One row of wallet history, as the crate reports it.
 *
 * Balances are signed: negative is outbound, positive inbound. [effectiveBalanceSat] is the truth
 * once a movement completes; before that only [intendedBalanceSat] means anything, so a caller
 * rendering an unsettled row must use the latter.
 *
 * [sentTo] and [receivedOn] hold raw destination strings (Ark address, on-chain address, BOLT11
 * invoice). Both being empty is normal — a board or a refresh has no counterparty.
 */
data class FfiMovement(
    val id: Int,
    val status: FfiMovementState,
    val effectiveBalanceSat: Long,
    val intendedBalanceSat: Long,
    val offchainFeeSat: Long,
    val sentTo: List<String>,
    val receivedOn: List<String>,
    val createdAtEpochSeconds: Long,
)

/**
 * Where a movement has got to, mirroring the crate's own enum.
 *
 * [PENDING] rows have no meaningful effective amount yet — see [FfiMovement.intendedBalanceSat].
 * [FAILED] and [CANCELED] rows are not part of the money timeline and the mappers drop them.
 */
enum class FfiMovementState { PENDING, SUCCESSFUL, FAILED, CANCELED }

/**
 * The wallet's spendable VTXOs, summarised.
 *
 * [soonestExpiryHeight] is null when there are no spendable VTXOs — distinct from a height of zero,
 * which would read as already-expired. [tipHeight] comes back with it so the countdown is computed
 * from the same read rather than from a separately-fetched, possibly staler, tip.
 */
data class FfiVtxoSummary(
    val count: Int,
    val totalSat: Long,
    val soonestExpiryHeight: Long?,
    val tipHeight: Long,
)

/**
 * The on-chain balance, split by what boarding can actually consume.
 *
 * [confirmedSat] is spendable now; [pendingSat] has been seen but cannot be boarded yet. The
 * split is the point: "your deposit arrived" and "you can board it" are different states.
 */
data class FfiOnchainBalance(
    val confirmedSat: Long,
    val pendingSat: Long,
    val totalSat: Long,
)
