#!/usr/bin/env bash
# Build lark-ffi as an XCFramework for iOS (device + simulator) and refresh the
# committed Swift bindings (U3). Runs locally / on a manual/nightly lane — not on
# the per-PR gate (KTD-9). Requires Xcode and the iOS Rust targets:
#   rustup target add aarch64-apple-ios aarch64-apple-ios-sim
#
# arm64 only, on purpose. The app excludes x86_64 for the simulator
# ("EXCLUDED_ARCHS[sdk=iphonesimulator*]" in iosApp/project.yml) because the Kotlin
# framework builds iosArm64 + iosSimulatorArm64 and no iosX64 target — so an x86_64
# slice here could never be linked, and building one costs a full release build of
# bark + LDK. Add x86_64 back (with a lipo'd fat simulator slice) only alongside an
# iosX64() target in composeApp.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FFI_DIR="$REPO_ROOT/rust/lark-ffi"
BUILD="$FFI_DIR/target"
OUT="$REPO_ROOT/iosApp/Frameworks"
GLUE_DIR="$REPO_ROOT/iosApp/iosApp/Generated"
LIB=liblark_ffi.a

# protoc is a hard build dependency: bark-server-rpc's build.rs compiles the captaind
# protos via prost-build. Easy to miss locally, where it is usually brew-installed.
if ! command -v protoc >/dev/null 2>&1; then
  echo "error: protoc not found — 'brew install protobuf' (bark-server-rpc's build.rs needs it)." >&2
  exit 1
fi

cd "$FFI_DIR"

# Must match iosApp/project.yml's deploymentTarget. Rust itself honours this, and so does the
# `cc` crate for the C dependencies (ring, secp256k1, sqlite) — without it they compile against
# the current SDK and every object file links with
#   "was built for newer 'iOS' version (26.5) than being linked (16.0)".
# Warnings only at link time, but the risk is real: C code compiled against a newer SDK can
# reference symbols an iOS 16 device does not have, which surfaces as a runtime crash on an old
# device instead of a build failure here.
export IPHONEOS_DEPLOYMENT_TARGET=16.0

echo "==> building iOS device + simulator static libs (arm64, min iOS $IPHONEOS_DEPLOYMENT_TARGET)"
cargo build --release --target aarch64-apple-ios
cargo build --release --target aarch64-apple-ios-sim

echo "==> generating Swift bindings + headers"
HDR="$BUILD/swift-headers"
rm -rf "$HDR"; mkdir -p "$HDR"
# --no-format: uniffi-bindgen shells out to a formatter when one is on PATH, which makes
# the generated bytes environment-dependent and the drift check below spuriously red.
cargo run --quiet --bin uniffi-bindgen -- generate \
  --library "$BUILD/aarch64-apple-ios/release/$LIB" \
  --language swift --no-format --out-dir "$HDR"
# UniFFI emits <name>FFI.modulemap; XCFramework expects module.modulemap.
cp "$HDR"/*FFI.modulemap "$HDR/module.modulemap"

echo "==> assembling XCFramework"
rm -rf "$OUT/lark_ffiFFI.xcframework"
mkdir -p "$OUT"
xcodebuild -create-xcframework \
  -library "$BUILD/aarch64-apple-ios/release/$LIB" -headers "$HDR" \
  -library "$BUILD/aarch64-apple-ios-sim/release/$LIB" -headers "$HDR" \
  -output "$OUT/lark_ffiFFI.xcframework"

# The glue is a committed source file (the app target compiles it), so a rebuild that
# changes the Rust surface must show up as a reviewable diff rather than a local-only
# artifact. Same contract as the committed Kotlin bindings.
echo "==> refreshing committed Swift glue at iosApp/iosApp/Generated"
mkdir -p "$GLUE_DIR"
cp "$HDR/lark_ffi.swift" "$GLUE_DIR/lark_ffi.swift"

echo "==> XCFramework at $OUT/lark_ffiFFI.xcframework"
echo "    Swift glue refreshed: $GLUE_DIR/lark_ffi.swift (commit any diff)"
