#!/usr/bin/env bash
# Build lark-ffi as an XCFramework for iOS and refresh the committed Swift bindings (U3).
# Requires Xcode and the iOS Rust targets:
#   rustup target add aarch64-apple-ios aarch64-apple-ios-sim
#
# Two modes:
#   (default)      device + simulator, release — the artifact a TestFlight archive links.
#   FFI_SIM_ONLY=1 simulator only — enough to build and run the app on a simulator, which is what
#                  the per-PR lane needs. Combined with FFI_PROFILE=debug it reuses the debug
#                  artifacts the Rust leg has already built, so CI pays for one extra target
#                  instead of two release builds of bark + LDK (KTD-9 keeps the full artifact off
#                  the per-PR gate; this keeps the *app build* on it, which is the part that broke).
#
# FFI_CHECK_GLUE=1 verifies the committed Swift glue instead of overwriting it, mirroring the
# committed-Kotlin-bindings drift check.
#
# arm64 only, on purpose. The app excludes x86_64 for the simulator
# ("EXCLUDED_ARCHS[sdk=iphonesimulator*]" in iosApp/project.yml) because the Kotlin
# framework builds iosArm64 + iosSimulatorArm64 and no iosX64 target — so an x86_64
# slice here could never be linked, and building one costs a full release build of
# bark + LDK. Add x86_64 back (with a lipo'd fat simulator slice) only alongside an
# iosX64() target in composeApp.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FFI_DIR="$REPO_ROOT/rust/lark-ffi"
BUILD="$FFI_DIR/target"
OUT="$REPO_ROOT/iosApp/Frameworks"
GLUE_DIR="$REPO_ROOT/iosApp/iosApp/Generated"
LIB=liblark_ffi.a
PROFILE="${FFI_PROFILE:-release}"
CARGO_PROFILE_FLAG=""
[ "$PROFILE" = "release" ] && CARGO_PROFILE_FLAG="--release"

# protoc is a hard build dependency: bark-server-rpc's build.rs compiles the captaind
# protos via prost-build. Easy to miss locally, where it is usually brew-installed.
if ! command -v protoc >/dev/null 2>&1; then
  echo "error: protoc not found — 'brew install protobuf' (bark-server-rpc's build.rs needs it)." >&2
  exit 1
fi

cd "$FFI_DIR"

# Must match iosApp/project.yml's deploymentTarget. Rust itself honours this, and so does the
# `cc` crate for the C dependencies (ring, secp256k1, sqlite) — without it they compile against
# the current SDK and every object file links with
#   "was built for newer 'iOS' version (26.5) than being linked (16.0)".
# Warnings only at link time, but the risk is real: C code compiled against a newer SDK can
# reference symbols an iOS 16 device does not have, which surfaces as a runtime crash on an old
# device instead of a build failure here.
export IPHONEOS_DEPLOYMENT_TARGET=16.0

if [ -n "${FFI_SIM_ONLY:-}" ]; then
  echo "==> building the iOS simulator static lib only ($PROFILE, min iOS $IPHONEOS_DEPLOYMENT_TARGET)"
  cargo build ${CARGO_PROFILE_FLAG} --target aarch64-apple-ios-sim
else
  echo "==> building iOS device + simulator static libs (arm64, $PROFILE, min iOS $IPHONEOS_DEPLOYMENT_TARGET)"
  cargo build ${CARGO_PROFILE_FLAG} --target aarch64-apple-ios
  cargo build ${CARGO_PROFILE_FLAG} --target aarch64-apple-ios-sim
fi

# Whichever slice exists drives bindgen; the generated API does not depend on target or profile.
BINDGEN_LIB="$BUILD/aarch64-apple-ios/$PROFILE/$LIB"
[ -f "$BINDGEN_LIB" ] || BINDGEN_LIB="$BUILD/aarch64-apple-ios-sim/$PROFILE/$LIB"

echo "==> generating Swift bindings + headers"
HDR="$BUILD/swift-headers"
rm -rf "$HDR"; mkdir -p "$HDR"
# --no-format: uniffi-bindgen shells out to a formatter when one is on PATH, which makes
# the generated bytes environment-dependent and the drift check below spuriously red.
cargo run --quiet --bin uniffi-bindgen -- generate \
  --library "$BINDGEN_LIB" \
  --language swift --no-format --out-dir "$HDR"
# UniFFI emits <name>FFI.modulemap; XCFramework expects module.modulemap.
cp "$HDR"/*FFI.modulemap "$HDR/module.modulemap"

echo "==> assembling XCFramework"
rm -rf "$OUT/lark_ffiFFI.xcframework"
mkdir -p "$OUT"
slices=(-library "$BUILD/aarch64-apple-ios-sim/$PROFILE/$LIB" -headers "$HDR")
if [ -z "${FFI_SIM_ONLY:-}" ]; then
  slices=(-library "$BUILD/aarch64-apple-ios/$PROFILE/$LIB" -headers "$HDR" "${slices[@]}")
fi
xcodebuild -create-xcframework "${slices[@]}" -output "$OUT/lark_ffiFFI.xcframework"

# The glue is a committed source file (the app target compiles it), so a rebuild that
# changes the Rust surface must show up as a reviewable diff rather than a local-only
# artifact. Same contract as the committed Kotlin bindings.
if [ -n "${FFI_CHECK_GLUE:-}" ]; then
  echo "==> checking the committed Swift glue against the crate"
  if ! diff -q "$HDR/lark_ffi.swift" "$GLUE_DIR/lark_ffi.swift" >/dev/null 2>&1; then
    echo "error: the committed Swift glue differs from the crate." >&2
    echo "       run scripts/build-xcframework.sh and commit iosApp/iosApp/Generated/lark_ffi.swift." >&2
    exit 1
  fi
else
  echo "==> refreshing committed Swift glue at iosApp/iosApp/Generated"
  mkdir -p "$GLUE_DIR"
  cp "$HDR/lark_ffi.swift" "$GLUE_DIR/lark_ffi.swift"
fi

echo "==> XCFramework at $OUT/lark_ffiFFI.xcframework"
[ -z "${FFI_CHECK_GLUE:-}" ] && echo "    Swift glue refreshed: $GLUE_DIR/lark_ffi.swift (commit any diff)"
exit 0
