#!/usr/bin/env bash
# Regenerate the committed UniFFI Kotlin bindings from the lark-ffi crate (plan KTD-2).
#
# The bindings are checked in so `./gradlew detekt :composeApp:testDebugUnitTest` works on a
# checkout with no Rust toolchain and no fork clones. This script is the ONLY sanctioned way to
# change them — never hand-edit the output. CI runs this same script and diffs the result, so a
# hand edit (or a stale commit after a crate change) fails the drift check.
#
# Requires the sibling fork checkouts at the rust/fork-pins.toml SHAs; scripts/build-rust.sh
# verifies that before building.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FFI_DIR="$REPO_ROOT/rust/lark-ffi"
OUT_DIR="$REPO_ROOT/composeApp/src/androidMain/kotlin"

# The dylib is the bindgen input in UniFFI 0.28 library mode, so it must exist and be current.
if [ "${SKIP_BUILD:-0}" != "1" ]; then
  ( cd "$FFI_DIR" && cargo build )
fi

LIB="$FFI_DIR/target/debug/liblark_ffi.dylib"
[ -f "$LIB" ] || LIB="$FFI_DIR/target/debug/liblark_ffi.so"
if [ ! -f "$LIB" ]; then
  echo "ERROR: no built lark-ffi library found under $FFI_DIR/target/debug" >&2
  echo "       run without SKIP_BUILD=1, or build the crate first." >&2
  exit 1
fi

echo "==> uniffi-bindgen (kotlin) from $(basename "$LIB")"
# --no-format is what makes the drift check meaningful: uniffi-bindgen otherwise tries to run
# ktlint on its output, so the generated bytes would depend on whether ktlint happens to be on
# PATH. That would make the committed bindings match on one machine and drift on another.
( cd "$FFI_DIR" && cargo run --quiet --bin uniffi-bindgen -- generate \
    --library "$LIB" \
    --language kotlin \
    --no-format \
    --out-dir "$OUT_DIR" )

echo "==> bindings written under composeApp/src/androidMain/kotlin/uniffi/"
